application: ffinder-74ebd
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /login_user
  script: login_user.php
  secure: always
  
- url: /watched_ads
  script: watched_ads.php
  secure: always

- url: /use_promo
  script: use_promo.php
  secure: always
