# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FFfinder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FFfinder

  pod "Firebase/Core"
  pod "Firebase/Messaging"
  pod "Firebase/Auth"
  pod "Firebase/Database"
  pod "EVReflection", :git => 'https://github.com/evermeer/EVReflection.git', :branch => 'Swift3'
  pod 'PopupDialog', '~> 0.5'
  pod 'DLRadioButton', '~> 1.4'

  target 'FFfinderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FFfinderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
