# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FFfinder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FFfinder

  pod ‘Firebase/Core’
  pod ‘Firebase/Messaging’
  pod ‘Firebase/Auth’
	
  target 'FFfinderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FFfinderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
